USE COUNTRY

-- POPULATION BY CONTINENT(2023)
SELECT SUM(POPULATION_2023) AS POPULATION_2023,UN_CONTINENTAL_REGION  FROM COUNTRY_DATA
GROUP BY UN_CONTINENTAL_REGION;

-- POPULATION BY CONTINENT(2022)
SELECT SUM(POPULATION_2022) AS POPULATION_2022 ,UN_CONTINENTAL_REGION  FROM COUNTRY_DATA
GROUP BY UN_CONTINENTAL_REGION;

-- POPULATION CHANGE BY CONTINENT(2022/23)
SELECT SUM(POPULATION_CHANGE) AS POPULATION_CHANGE,UN_CONTINENTAL_REGION  FROM COUNTRY_DATA
GROUP BY UN_CONTINENTAL_REGION;

-- POPULATION CHANGE BY SUBREGIONS(2022/23)
SELECT TOP 10 SUM(POPULATION_CHANGE) AS POPULATION_CHANGE, UN_STATISTICAL_SUBREGION, UN_CONTINENTAL_REGION FROM COUNTRY_DATA
GROUP BY UN_CONTINENTAL_REGION, UN_STATISTICAL_SUBREGION
ORDER BY POPULATION_CHANGE DESC;

