USE COUNTRY;

-- TOTAL WATER BY CONTINENT
SELECT SUM(WATER_IN_KM2) AS TOTAL_WATER, UN_CONTINENTAL_REGION FROM COUNTRY_DATA
GROUP BY UN_CONTINENTAL_REGION

-- TOTAL WATER BY COUNTRY
SELECT TOP 5 WATER_IN_KM2 AS TOTAL_WATER, COUNTRY FROM COUNTRY_DATA
ORDER BY WATER_IN_KM2 DESC;

-- TOTAL WATER AND FORECASTED GDP
WITH RANKEDCOUNTRIES AS (
    SELECT
        WATER_IN_KM2, 
		WORLD_BANK_FORECAST_GDP_PPP,
        COUNTRY,
        UN_CONTINENTAL_REGION,
        ROW_NUMBER() OVER (PARTITION BY UN_CONTINENTAL_REGION ORDER BY WATER_IN_KM2 DESC) AS ROWNUM
    FROM
        COUNTRY_DATA
)
SELECT
    WATER_IN_KM2,WORLD_BANK_FORECAST_GDP_PPP,
    COUNTRY,
    UN_CONTINENTAL_REGION
FROM
    RANKEDCOUNTRIES
WHERE
    ROWNUM = 1;
